
# Initialize the stdArrays plugins.
NDStdArraysConfigure("$(DEVICE_NAME)_ch0_stdarrays", $(STDARRAYS_QUEUE_SIZE), $(STDARRAYS_BLOCKING_CALLBACKS), "$(DEVICE_NAME)_channels", 0, $(STDARRAYS_MAX_MEMORY), $(STDARRAYS_PRIORITY), $(STDARRAYS_STACK_SIZE))
NDStdArraysConfigure("$(DEVICE_NAME)_ch1_stdarrays", $(STDARRAYS_QUEUE_SIZE), $(STDARRAYS_BLOCKING_CALLBACKS), "$(DEVICE_NAME)_channels", 1, $(STDARRAYS_MAX_MEMORY), $(STDARRAYS_PRIORITY), $(STDARRAYS_STACK_SIZE))
NDStdArraysConfigure("$(DEVICE_NAME)_ch2_stdarrays", $(STDARRAYS_QUEUE_SIZE), $(STDARRAYS_BLOCKING_CALLBACKS), "$(DEVICE_NAME)_channels", 2, $(STDARRAYS_MAX_MEMORY), $(STDARRAYS_PRIORITY), $(STDARRAYS_STACK_SIZE))
NDStdArraysConfigure("$(DEVICE_NAME)_ch3_stdarrays", $(STDARRAYS_QUEUE_SIZE), $(STDARRAYS_BLOCKING_CALLBACKS), "$(DEVICE_NAME)_channels", 3, $(STDARRAYS_MAX_MEMORY), $(STDARRAYS_PRIORITY), $(STDARRAYS_STACK_SIZE))
NDStdArraysConfigure("$(DEVICE_NAME)_ch4_stdarrays", $(STDARRAYS_QUEUE_SIZE), $(STDARRAYS_BLOCKING_CALLBACKS), "$(DEVICE_NAME)_channels", 4, $(STDARRAYS_MAX_MEMORY), $(STDARRAYS_PRIORITY), $(STDARRAYS_STACK_SIZE))
NDStdArraysConfigure("$(DEVICE_NAME)_ch5_stdarrays", $(STDARRAYS_QUEUE_SIZE), $(STDARRAYS_BLOCKING_CALLBACKS), "$(DEVICE_NAME)_channels", 5, $(STDARRAYS_MAX_MEMORY), $(STDARRAYS_PRIORITY), $(STDARRAYS_STACK_SIZE))
NDStdArraysConfigure("$(DEVICE_NAME)_ch6_stdarrays", $(STDARRAYS_QUEUE_SIZE), $(STDARRAYS_BLOCKING_CALLBACKS), "$(DEVICE_NAME)_channels", 6, $(STDARRAYS_MAX_MEMORY), $(STDARRAYS_PRIORITY), $(STDARRAYS_STACK_SIZE))
NDStdArraysConfigure("$(DEVICE_NAME)_ch7_stdarrays", $(STDARRAYS_QUEUE_SIZE), $(STDARRAYS_BLOCKING_CALLBACKS), "$(DEVICE_NAME)_channels", 7, $(STDARRAYS_MAX_MEMORY), $(STDARRAYS_PRIORITY), $(STDARRAYS_STACK_SIZE))
