# Load records for each chanel.
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH0, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=0")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH0, STDAR_PORT=$(DEVICE_NAME)_ch0_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("db/TRCAEN_Channel.db", "PREFIX=$(PREFIX):CH0, PORT=$(DEVICE_NAME), CHANNEL=0")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH1, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=1")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH1, STDAR_PORT=$(DEVICE_NAME)_ch1_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("db/TRCAEN_Channel.db", "PREFIX=$(PREFIX):CH1, PORT=$(DEVICE_NAME), CHANNEL=1")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH2, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=2")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH2, STDAR_PORT=$(DEVICE_NAME)_ch2_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("db/TRCAEN_Channel.db", "PREFIX=$(PREFIX):CH2, PORT=$(DEVICE_NAME), CHANNEL=2")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH3, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=3")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH3, STDAR_PORT=$(DEVICE_NAME)_ch3_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("db/TRCAEN_Channel.db", "PREFIX=$(PREFIX):CH3, PORT=$(DEVICE_NAME), CHANNEL=3")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH4, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=4")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH4, STDAR_PORT=$(DEVICE_NAME)_ch4_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("db/TRCAEN_Channel.db", "PREFIX=$(PREFIX):CH4, PORT=$(DEVICE_NAME), CHANNEL=4")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH5, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=5")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH5, STDAR_PORT=$(DEVICE_NAME)_ch5_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("db/TRCAEN_Channel.db", "PREFIX=$(PREFIX):CH5, PORT=$(DEVICE_NAME), CHANNEL=5")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH6, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=6")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH6, STDAR_PORT=$(DEVICE_NAME)_ch6_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("db/TRCAEN_Channel.db", "PREFIX=$(PREFIX):CH6, PORT=$(DEVICE_NAME), CHANNEL=6")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH7, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=7")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH7, STDAR_PORT=$(DEVICE_NAME)_ch7_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("db/TRCAEN_Channel.db", "PREFIX=$(PREFIX):CH7, PORT=$(DEVICE_NAME), CHANNEL=7")
